/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as WikiPageIdRouteImport } from './routes/wiki/$pageId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiPageIdRoute = WikiPageIdRouteImport.update({
  id: '/wiki/$pageId',
  path: '/wiki/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/wiki/$pageId': typeof WikiPageIdRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/wiki/$pageId': typeof WikiPageIdRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/wiki/$pageId': typeof WikiPageIdRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sources/$sourceId'
    | '/tasks/$taskId'
    | '/wiki/$pageId'
    | '/approvals/'
    | '/sources/'
    | '/tasks/'
    | '/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sources/$sourceId'
    | '/tasks/$taskId'
    | '/wiki/$pageId'
    | '/approvals'
    | '/sources'
    | '/tasks'
    | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/sources/$sourceId'
    | '/tasks/$taskId'
    | '/wiki/$pageId'
    | '/approvals/'
    | '/sources/'
    | '/tasks/'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  WikiPageIdRoute: typeof WikiPageIdRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$pageId': {
      id: '/wiki/$pageId'
      path: '/wiki/$pageId'
      fullPath: '/wiki/$pageId'
      preLoaderRoute: typeof WikiPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  WikiPageIdRoute: WikiPageIdRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
